# Generated by Django 4.1.7 on 2023-05-03 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='user',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
